In [282]:
#importamos las librerias 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import lightgbm as lgb

from sklearn.ensemble import ExtraTreesRegressor
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import RobustScaler
from sklearn.datasets import load_digits

from sklearn.preprocessing import StandardScaler

from sklearn.decomposition import PCA
from sklearn.tree import DecisionTreeRegressor

from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import root_mean_squared_error

 
from sklearn import datasets
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor

from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

# Cleaning-3-feuture engineering-Eliminacion de outlayers-one-coding

In [360]:
paht= './data/diamonds_train.csv'   #leemos el archivos csv que esta en la carpeta data
data = pd.read_csv(paht, sep= ",")

In [359]:
data

,price,carat,city,depth,table,x,y,z,cut,color,clarity
0,4268,1.21,Dubai,62.4,58.0,6.83,6.79,4.25,Premium,J,VS2
1,505,0.32,Kimberly,63.0,57.0,4.35,4.38,2.75,Very Good,H,VS2
2,2686,0.71,Las Vegas,65.5,55.0,5.62,5.53,3.65,Fair,G,VS1
3,738,0.41,Kimberly,63.8,56.0,4.68,4.72,3.00,Good,D,SI1
4,4882,1.02,Dubai,60.5,59.0,6.55,6.51,3.95,Ideal,G,SI1
...,...,...,...,...,...,...,...,...,...,...,...
40450,10070,1.34,Antwerp,62.7,57.0,7.10,7.04,4.43,Ideal,G,VS1
40451,12615,2.02,Madrid,57.1,60.0,8.31,8.25,4.73,Good,F,SI2
40452,5457,1.01,Kimberly,62.7,56.0,6.37,6.42,4.01,Ideal,H,SI1
40453,456,0.33,Kimberly,61.9,54.3,4.45,4.47,2.76,Ideal,J,VS1
40454,6232,1.24,London,62.0,58.0,6.83,6.88,4.25,Ideal,I,SI1

In [362]:
data['volume'] = data['x'] * data['y'] * data['z']

In [363]:
import pandas as pd
from sklearn.preprocessing import RobustScaler


# Realizar feature engineering
data['volume_per_carat'] = data['volume'] / data['carat']
data['depth_to_table_ratio'] = data['depth'] / data['table']
data['carat_depth_interaction'] = data['carat'] * data['depth']
data['log_volume'] = np.log(data['volume'] + 1)

# Seleccionar las columnas numÃ©ricas para escalar
numerical_features = ['carat', 'depth', 'table', 'x', 'y', 'z', 'volume', 
                     'volume_per_carat', 'depth_to_table_ratio',
                     'carat_depth_interaction', 'log_volume']

# Inicializar el RobustScaler
scaler = RobustScaler()

# Aplicar el scaler a las columnas seleccionadas
data[numerical_features] = scaler.fit_transform(data[numerical_features])

# Ahora tus datos estÃ¡n escalados
print(data.head())

   price     carat       city     depth     table         x         y  \
0   4268  0.796875      Dubai  0.400000  0.333333  0.622951  0.593407
1    505 -0.593750   Kimberly  0.800000  0.000000 -0.732240 -0.730769
2   2686  0.015625  Las Vegas  2.466667 -0.666667 -0.038251 -0.098901
3    738 -0.453125   Kimberly  1.333333 -0.333333 -0.551913 -0.543956
4   4882  0.500000      Dubai -0.866667  0.666667  0.469945  0.439560

          z        cut color clarity    volume  volume_per_carat  \
0  0.648889    Premium     J     VS2  0.777758         -0.155981
1 -0.684444  Very Good     H     VS2 -0.587925          0.067012
2  0.115556       Fair     G     VS1 -0.011821         -0.977419
3 -0.462222       Good     D     SI1 -0.456992         -0.487401
4  0.382222      Ideal     G     SI1  0.507202          0.433207

   depth_to_table_ratio  carat_depth_interaction  log_volume
0             -0.099989                 0.791286    0.561069
1              0.345832                -0.578785   -0.806561
2              1.644515                 0.073400   -0.011355
3              0.861729                -0.430301   -0.565623
4             -0.864805                 0.449808    0.398004

In [371]:
#Volvemos las variables categoricas en numericas 
#data = pd.get_dummies(data, columns=["city","cut","color","clarity",], dtype=int)

In [315]:
#Volumen: Calcular el volumen del diamante como una nueva caracterÃ­stica:
#diamons_cleaning_3['volume'] = diamons_cleaning_3['x'] * diamons_cleaning_3['y'] * diamons_cleaning_3['z']

In [316]:
#diamons_cleaning_3

,price,carat,city,depth,table,x,y,z,cut,color,clarity,volume
0,4268,1.21,Dubai,62.4,58.0,6.83,6.79,4.25,Premium,J,VS2,197.096725
1,505,0.32,Kimberly,63.0,57.0,4.35,4.38,2.75,Very Good,H,VS2,52.395750
2,2686,0.71,Las Vegas,65.5,55.0,5.62,5.53,3.65,Fair,G,VS1,113.436890
3,738,0.41,Kimberly,63.8,56.0,4.68,4.72,3.00,Good,D,SI1,66.268800
4,4882,1.02,Dubai,60.5,59.0,6.55,6.51,3.95,Ideal,G,SI1,168.429975
...,...,...,...,...,...,...,...,...,...,...,...,...
40450,10070,1.34,Antwerp,62.7,57.0,7.10,7.04,4.43,Ideal,G,VS1,221.429120
40451,12615,2.02,Madrid,57.1,60.0,8.31,8.25,4.73,Good,F,SI2,324.276975
40452,5457,1.01,Kimberly,62.7,56.0,6.37,6.42,4.01,Ideal,H,SI1,163.990554
40453,456,0.33,Kimberly,61.9,54.3,4.45,4.47,2.76,Ideal,J,VS1,54.900540
40454,6232,1.24,London,62.0,58.0,6.83,6.88,4.25,Ideal,I,SI1,199.709200

In [319]:
#Volvemos las variables categoricas en numericas 
diamons_cleaning_3 = pd.get_dummies(diamons_cleaning_3, columns=["city","cut","color","clarity",], dtype=int)

In [427]:
numerical_columns = ['carat', 'depth', 'table', 'x', 'y', 'z', 'volume', 
                     'volume_per_carat', 'depth_to_table_ratio',
                     'carat_depth_interaction', 'log_volume']

In [432]:
data

,price,carat,depth,table,x,y,z,volume,volume_per_carat,depth_to_table_ratio,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,4268,0.796875,0.400000,0.333333,0.622951,0.593407,0.648889,0.777758,-0.155981,-0.099989,...,0,1,0,0,0,0,0,1,0,0
1,505,-0.593750,0.800000,0.000000,-0.732240,-0.730769,-0.684444,-0.587925,0.067012,0.345832,...,0,0,0,0,0,0,0,1,0,0
2,2686,0.015625,2.466667,-0.666667,-0.038251,-0.098901,0.115556,-0.011821,-0.977419,1.644515,...,0,0,0,0,0,0,1,0,0,0
3,738,-0.453125,1.333333,-0.333333,-0.551913,-0.543956,-0.462222,-0.456992,-0.487401,0.861729,...,0,0,0,0,1,0,0,0,0,0
4,4882,0.500000,-0.866667,0.666667,0.469945,0.439560,0.382222,0.507202,0.433207,-0.864805,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40449,3710,0.015625,0.066667,-0.333333,0.000000,0.005495,0.008889,0.001896,-0.438432,0.347257,...,0,0,0,0,0,0,1,0,0,0
40450,10070,1.000000,0.600000,0.000000,0.770492,0.730769,0.808889,1.007407,0.464328,0.266025,...,0,0,0,0,0,0,1,0,0,0
40452,5457,0.484375,0.600000,-0.333333,0.371585,0.390110,0.435556,0.465303,-0.293688,0.563877,...,0,0,0,0,1,0,0,0,0,0
40453,456,-0.578125,0.066667,-0.900000,-0.677596,-0.681319,-0.675556,-0.564285,0.759152,0.872002,...,0,1,0,0,0,0,1,0,0,0
40454,6232,0.843750,0.133333,0.333333,0.622951,0.642857,0.648889,0.802415,-0.638916,-0.204564,...,1,0,0,0,1,0,0,0,0,0

In [324]:
scaler = RobustScaler()
diamons_cleaning_3[numerical_columns] = scaler.fit_transform(diamons_cleaning_3[numerical_columns])

In [428]:
from scipy import stats

# Eliminar outliers utilizando Z-scores
#z_scores = np.abs(stats.zscore(data[numerical_columns]))
#threshold = 3
#filtered_entries = (z_scores < threshold).all(axis=1)
#data = data[filtered_entries]

# Mostrar las primeras filas del DataFrame despuÃ©s de eliminar outliers
#print(data.head())
#print(f"NÃºmero de filas despuÃ©s de eliminar outliers: {data.shape[0]}")

   price     carat     depth     table         x         y         z  \
0   4268  0.796875  0.400000  0.333333  0.622951  0.593407  0.648889
1    505 -0.593750  0.800000  0.000000 -0.732240 -0.730769 -0.684444
2   2686  0.015625  2.466667 -0.666667 -0.038251 -0.098901  0.115556
3    738 -0.453125  1.333333 -0.333333 -0.551913 -0.543956 -0.462222
4   4882  0.500000 -0.866667  0.666667  0.469945  0.439560  0.382222

     volume  volume_per_carat  depth_to_table_ratio  ...  color_I  color_J  \
0  0.777758         -0.155981             -0.099989  ...        0        1
1 -0.587925          0.067012              0.345832  ...        0        0
2 -0.011821         -0.977419              1.644515  ...        0        0
3 -0.456992         -0.487401              0.861729  ...        0        0
4  0.507202          0.433207             -0.864805  ...        0        0

   clarity_I1  clarity_IF  clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  \
0           0           0            0            0            0            1
1           0           0            0            0            0            1
2           0           0            0            0            1            0
3           0           0            1            0            0            0
4           0           0            1            0            0            0

   clarity_VVS1  clarity_VVS2
0             0             0
1             0             0
2             0             0
3             0             0
4             0             0

[5 rows x 45 columns]
NÃºmero de filas despuÃ©s de eliminar outliers: 39343

In [430]:
#Separar las caracterÃ­sticas (X) y el objetivo (y):
X = data.drop('price', axis=1)
y = data['price']

In [431]:
#Dividir el conjunto de datos en entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [415]:
diamons_cleaning_3

,price,carat,depth,table,x,y,z,volume,carat_depth,carat_table,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,4268,0.796875,0.400000,0.333333,0.622951,0.593407,0.648889,0.777758,0.791286,70.180,...,0,1,0,0,0,0,0,1,0,0
1,505,-0.593750,0.800000,0.000000,-0.732240,-0.730769,-0.684444,-0.587925,-0.578785,18.240,...,0,0,0,0,0,0,0,1,0,0
2,2686,0.015625,2.466667,-0.666667,-0.038251,-0.098901,0.115556,-0.011821,0.073400,39.050,...,0,0,0,0,0,0,1,0,0,0
3,738,-0.453125,1.333333,-0.333333,-0.551913,-0.543956,-0.462222,-0.456992,-0.430301,22.960,...,0,0,0,0,1,0,0,0,0,0
4,4882,0.500000,-0.866667,0.666667,0.469945,0.439560,0.382222,0.507202,0.449808,60.180,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40449,3710,0.015625,0.066667,-0.333333,0.000000,0.005495,0.008889,0.001896,0.010125,39.760,...,0,0,0,0,0,0,1,0,0,0
40450,10070,1.000000,0.600000,0.000000,0.770492,0.730769,0.808889,1.007407,1.002055,76.380,...,0,0,0,0,0,0,1,0,0,0
40452,5457,0.484375,0.600000,-0.333333,0.371585,0.390110,0.435556,0.465303,0.489838,56.560,...,0,0,0,0,1,0,0,0,0,0
40453,456,-0.578125,0.066667,-0.900000,-0.677596,-0.681319,-0.675556,-0.564285,-0.572175,17.919,...,0,1,0,0,0,0,1,0,0,0
40454,6232,0.843750,0.133333,0.333333,0.622951,0.642857,0.648889,0.802415,0.825350,71.920,...,1,0,0,0,1,0,0,0,0,0

,price,carat,depth,table,x,y,z,volume,volume_per_carat,depth_to_table_ratio,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,4268,0.796875,0.400000,0.333333,0.622951,0.593407,0.648889,0.777758,-0.155981,-0.099989,...,0,1,0,0,0,0,0,1,0,0
1,505,-0.593750,0.800000,0.000000,-0.732240,-0.730769,-0.684444,-0.587925,0.067012,0.345832,...,0,0,0,0,0,0,0,1,0,0
2,2686,0.015625,2.466667,-0.666667,-0.038251,-0.098901,0.115556,-0.011821,-0.977419,1.644515,...,0,0,0,0,0,0,1,0,0,0
3,738,-0.453125,1.333333,-0.333333,-0.551913,-0.543956,-0.462222,-0.456992,-0.487401,0.861729,...,0,0,0,0,1,0,0,0,0,0
4,4882,0.500000,-0.866667,0.666667,0.469945,0.439560,0.382222,0.507202,0.433207,-0.864805,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40450,10070,1.000000,0.600000,0.000000,0.770492,0.730769,0.808889,1.007407,0.464328,0.266025,...,0,0,0,0,0,0,1,0,0,0
40451,12615,2.062500,-3.133333,1.000000,1.431694,1.395604,1.075556,1.978082,-0.776538,-1.983213,...,0,0,0,0,0,1,0,0,0,0
40452,5457,0.484375,0.600000,-0.333333,0.371585,0.390110,0.435556,0.465303,-0.293688,0.563877,...,0,0,0,0,1,0,0,0,0,0
40453,456,-0.578125,0.066667,-0.900000,-0.677596,-0.681319,-0.675556,-0.564285,0.759152,0.872002,...,0,1,0,0,0,0,1,0,0,0
40454,6232,0.843750,0.133333,0.333333,0.622951,0.642857,0.648889,0.802415,-0.638916,-0.204564,...,1,0,0,0,1,0,0,0,0,0

In [433]:
#LightGBM:
model_5 = lgb.LGBMRegressor(n_estimators=100, learning_rate=0.1, random_state=43)
model_5.fit(X, y)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001768 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2478
[LightGBM] [Info] Number of data points in the train set: 39343, number of used features: 44
[LightGBM] [Info] Start training from score 3826.109829

LGBMRegressor(random_state=43)

In [434]:
y_pred_5 = model_5.predict(X_test)
rmse_2 = np.sqrt(mean_squared_error(y_test, y_pred_5))
rmse_2

np.float64(447.24864101575986)

In [435]:
%%time
# Realizar validaciÃ³n cruzada y calcular el RMSE
scores = cross_val_score(model_5, 
                         X, 
                         y, 
                         scoring='neg_root_mean_squared_error', 
                         cv=5,
                         n_jobs=-1)

# Imprimir el tipo de modelo y los scores
print(type(model_5), '\n')
scores, 

# Calcular y mostrar el RMSE promedio
print(np.mean(-scores))

<class 'lightgbm.sklearn.LGBMRegressor'>

512.2520403711106
CPU times: total: 109 ms
Wall time: 13.9 s

In [417]:
model_5 = lgb.LGBMRegressor()

param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 5, 7],
    'num_leaves': [31, 50, 100]
}

In [454]:
%%time
grid_search = GridSearchCV(estimator=model_5, param_grid=param_grid, scoring='neg_root_mean_squared_error', cv=5, n_jobs=-1)
grid_search.fit(X_train, y_train)

print(f"Mejores parÃ¡metros: {grid_search.best_params_}")
print(f"Mejor RMSE: {-grid_search.best_score_}")

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004749 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2470
[LightGBM] [Info] Number of data points in the train set: 31474, number of used features: 44
[LightGBM] [Info] Start training from score 3839.123848
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Mejores parÃ¡metros: {'learning_rate': 0.1, 'max_depth': 7, 'n_estimators': 300, 'num_leaves': 31}
Mejor RMSE: 520.1238711362878
CPU times: total: 4.89 s
Wall time: 2min 21s

# Predicciones

In [386]:
paht= './data/diamonds_test.csv'
diamons_test = pd.read_csv(paht, sep= ",")

In [393]:
paht= './data/diamonds_test.csv'
data_test = pd.read_csv(paht, sep= ",")

In [394]:
#Volumen: Calcular el volumen del diamante como una nueva caracterÃ­stica:
data_test['volume'] = data_test['x'] * data_test['y'] * data_test['z']

In [395]:
import pandas as pd
from sklearn.preprocessing import RobustScaler


# Realizar feature engineering
data_test['volume_per_carat'] = data_test['volume'] / data_test['carat']
data_test['depth_to_table_ratio'] = data_test['depth'] / data_test['table']
data_test['carat_depth_interaction'] = data_test['carat'] * data_test['depth']
data_test['log_volume'] = np.log(data_test['volume'] + 1)

# Seleccionar las columnas numÃ©ricas para escalar
numerical_features = ['carat', 'depth', 'table', 'x', 'y', 'z', 'volume', 
                     'volume_per_carat', 'depth_to_table_ratio',
                     'carat_depth_interaction', 'log_volume']

# Inicializar el RobustScaler
scaler = RobustScaler()

# Aplicar el scaler a las columnas seleccionadas
data_test[numerical_features] = scaler.fit_transform(data_test[numerical_features])

# Ahora tus datos estÃ¡n escalados
print(data.head())

   price     carat     depth     table         x         y         z  \
0   4268  0.796875  0.400000  0.333333  0.622951  0.593407  0.648889
1    505 -0.593750  0.800000  0.000000 -0.732240 -0.730769 -0.684444
2   2686  0.015625  2.466667 -0.666667 -0.038251 -0.098901  0.115556
3    738 -0.453125  1.333333 -0.333333 -0.551913 -0.543956 -0.462222
4   4882  0.500000 -0.866667  0.666667  0.469945  0.439560  0.382222

     volume  volume_per_carat  depth_to_table_ratio  ...  color_I  color_J  \
0  0.777758         -0.155981             -0.099989  ...        0        1
1 -0.587925          0.067012              0.345832  ...        0        0
2 -0.011821         -0.977419              1.644515  ...        0        0
3 -0.456992         -0.487401              0.861729  ...        0        0
4  0.507202          0.433207             -0.864805  ...        0        0

   clarity_I1  clarity_IF  clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  \
0           0           0            0            0            0            1
1           0           0            0            0            0            1
2           0           0            0            0            1            0
3           0           0            1            0            0            0
4           0           0            1            0            0            0

   clarity_VVS1  clarity_VVS2
0             0             0
1             0             0
2             0             0
3             0             0
4             0             0

[5 rows x 45 columns]

In [396]:
data_test = data_test.drop("id", axis=1)

In [335]:
#Volumen: Calcular el volumen del diamante como una nueva caracterÃ­stica:
diamons_test['volume'] = diamons_test['x'] * diamons_test['y'] * diamons_test['z']

In [237]:
diamons_test['log_carat'] = np.log(diamons_test['carat'])

In [336]:
diamons_test['carat_depth'] = diamons_test['carat'] * diamons_test['depth']
diamons_test['carat_table'] = diamons_test['carat'] * diamons_test['table']
diamons_test['carat_x'] = diamons_test['carat'] * diamons_test['x']
diamons_test['carat_y'] = diamons_test['carat'] * diamons_test['y']
diamons_test['carat_z'] = diamons_test['carat'] * diamons_test['z']

In [399]:
#Volvemos las variables categoricas en numericas 
data_test = pd.get_dummies(data_test, columns=["city","cut","color","clarity",], dtype=int)

In [449]:
#paso 3
nueva = model_5.predict(data_test)

In [338]:
numerical_columns = ['carat', 'depth', 'table', 'x', 'y', 'z', 'volume',  'carat_depth']

In [339]:
scaler = RobustScaler()
diamons_test[numerical_columns] = scaler.fit_transform(diamons_test[numerical_columns])

In [340]:
diamons_test = diamons_test.drop("id", axis=1)

In [341]:
diamons_test

,carat,depth,table,x,y,z,volume,carat_depth,carat_table,carat_x,...,color_I,color_J,clarity_I1,clarity_IF,clarity_SI1,clarity_SI2,clarity_VS1,clarity_VS2,clarity_VVS1,clarity_VVS2
0,0.140625,0.533333,1.000000,0.066667,0.094444,0.125000,0.101505,0.145231,47.40,4.5978,...,0,0,0,0,1,0,0,0,0,0
1,0.781250,-0.600000,0.000000,0.616667,0.650000,0.580357,0.770379,0.734901,68.40,8.1720,...,0,1,0,0,0,0,1,0,0,0
2,1.359375,0.200000,1.333333,0.933333,0.888889,0.928571,1.253082,1.344180,95.77,11.5866,...,0,0,0,0,1,0,0,0,0,0
3,0.312500,1.266667,-1.000000,0.216667,0.227778,0.330357,0.289708,0.341738,48.60,5.4810,...,0,0,0,0,1,0,0,0,0,0
4,-0.312500,0.666667,0.333333,-0.361111,-0.350000,-0.303571,-0.315189,-0.305312,29.00,2.5250,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13480,-0.203125,0.000000,-0.333333,-0.194444,-0.222222,-0.205357,-0.201743,-0.209812,31.92,3.0495,...,0,0,0,0,1,0,0,0,0,0
13481,0.015625,0.200000,-0.666667,0.005556,0.005556,0.026786,0.012766,0.011411,39.05,4.0541,...,1,0,0,0,0,0,0,1,0,0
13482,0.000000,-0.200000,-0.666667,0.027778,-0.005556,0.000000,0.007264,-0.014551,38.50,4.0250,...,0,0,0,0,0,0,1,0,0,0
13483,0.000000,-2.066667,0.000000,0.083333,0.094444,-0.071429,0.035572,-0.063384,39.90,4.0950,...,0,0,0,0,0,1,0,0,0,0
13484,-0.468750,0.333333,-0.666667,-0.555556,-0.550000,-0.526786,-0.473444,-0.467012,22.00,1.8800,...,1,0,0,0,0,0,0,0,0,1

# Creamos la repuesta

In [346]:
#paso 3
y_pred_test = model_5.predict(diamons_test)

In [401]:
y_pred_test_2

array([2906.99175664, 5773.37086308, 9654.24266063, ..., 3008.92542709,
       2079.90363812,  770.4486849 ])

In [450]:
nueva

array([2888.27553848, 5669.62776924, 9918.91599212, ..., 2987.69943174,
       2082.82212863,  778.8648156 ])

In [348]:
y_pred_test

array([2823.59648121, 5525.50214075, 9550.59792525, ..., 3123.85025778,
       2142.98965024,  758.39881906])

In [451]:
# Convertir el array de NumPy en un DataFrame de pandas
nueva_df = pd.DataFrame(nueva, columns=['Price'])

# Mostrar las primeras filas del DataFrame
nueva_df.head()

         Price
0  2888.275538
1  5669.627769
2  9918.915992
3  3994.790171
4  1654.811339

In [452]:
nueva_df['id'] = nueva_df.index

In [408]:
y_pred_test_df

             Price
0      2823.596481
1      5525.502141
2      9550.597925
3      3909.427094
4      1679.168876
...            ...
13480  1600.069634
13481  2291.907721
13482  3123.850258
13483  2142.989650
13484   758.398819

[13485 rows x 1 columns]

In [453]:
#paso 5

# Guardar el DataFrame en un archivo CSV en la carpeta 'predictions'
nueva_df.to_csv('predictions/cleaning-4-model_5-LightGBM-RobustScaler-no-outlayers-3.csv', index=False)

print("El DataFrame ha sido guardado en la carpeta 'predictions'.")

El DataFrame ha sido guardado en la carpeta 'predictions'.

In [409]:
y_pred_test_df_3

             Price     id
0      2906.991757      0
1      5773.370863      1
2      9654.242661      2
3      4062.778052      3
4      1566.408844      4
...            ...    ...
13480  1589.571421  13480
13481  2295.287814  13481
13482  3008.925427  13482
13483  2079.903638  13483
13484   770.448685  13484

[13485 rows x 2 columns]

In [411]:
%%time
#RAMDON FOREST REGRESSOR
model_3 = RandomForestRegressor(n_estimators=100, random_state=42)
model_3.fit(X_train, y_train)
y_pred_3 = model_3.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_3))
print(f"Random Forest RMSE: {rmse}")

Random Forest RMSE: 563.3231349500733
CPU times: total: 44.2 s
Wall time: 44.4 s

In [412]:
%%time
# Realizar validaciÃ³n cruzada y calcular el RMSE
scores = cross_val_score(model_3, 
                         X, 
                         y, 
                         scoring='neg_root_mean_squared_error', 
                         cv=5,
                         n_jobs=-1)

# Imprimir el tipo de modelo y los scores
print(type(model_3), '\n')
print(scores, '\n')

# Calcular y mostrar el RMSE promedio
print(np.mean(-scores))

<class 'sklearn.ensemble._forest.RandomForestRegressor'>

[-549.87991296 -549.35130026 -559.45665312 -605.64654414 -539.28772206]

560.7244265072874
CPU times: total: 797 ms
Wall time: 2min 4s

In [257]:
#paso 3
y_pred_test_2 = model_3.predict(diamons_test)

In [260]:
# Convertir el array de NumPy en un DataFrame de pandas
y_pred_test_df_2 = pd.DataFrame(y_pred_test_2, columns=['Price'])

# Mostrar las primeras filas del DataFrame
y_pred_test_df_2.head()

     Price
0  2952.49
1  5444.34
2  9597.19
3  4121.13
4  1660.49

In [261]:
y_pred_test_df_2['id'] = y_pred_test_df_2.index

In [262]:
#paso 5

# Guardar el DataFrame en un archivo CSV en la carpeta 'predictions'
y_pred_test_df_2.to_csv('predictions/cleaning-3-model_5-RAMDON FOREST REGRESSOR-RobustScaler-no-outlayers-2.csv', index=False)

print("El DataFrame ha sido guardado en la carpeta 'predictions'.")

El DataFrame ha sido guardado en la carpeta 'predictions'.

In [413]:
%%time
#Extra Trees Regressor:


model_4 = ExtraTreesRegressor(n_estimators=100, random_state=42)
model_4.fit(X_train, y_train)
y_pred_4 = model_4.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_4))
print(f"Extra Trees RMSE: {rmse}")

Extra Trees RMSE: 548.4359476972343
CPU times: total: 32 s
Wall time: 32.4 s

In [414]:
%%time
# Realizar validaciÃ³n cruzada y calcular el RMSE
scores = cross_val_score(model_4, 
                         X, 
                         y, 
                         scoring='neg_root_mean_squared_error', 
                         cv=5,
                         n_jobs=-1)

# Imprimir el tipo de modelo y los scores
print(type(model_4), '\n')
print(scores, '\n')

# Calcular y mostrar el RMSE promedio
print(np.mean(-scores))

<class 'sklearn.ensemble._forest.ExtraTreesRegressor'>

[-546.95744786 -561.89364618 -552.65573989 -586.59605837 -555.34728839]

560.6900361369152
CPU times: total: 703 ms
Wall time: 1min 39s

In [265]:
#paso 3
y_pred_test_3 = model_4.predict(diamons_test)

In [266]:
# Convertir el array de NumPy en un DataFrame de pandas
y_pred_test_df_3 = pd.DataFrame(y_pred_test_3, columns=['Price'])

# Mostrar las primeras filas del DataFrame
y_pred_test_df_3.head()

     Price
0  2972.19
1  5416.80
2  9602.18
3  4100.76
4  1693.71

In [268]:
y_pred_test_df_3['id'] = y_pred_test_df_3.index

In [269]:
#paso 5

# Guardar el DataFrame en un archivo CSV en la carpeta 'predictions'
y_pred_test_df_2.to_csv('predictions/cleaning-3-model_5-Extra-Trees-Regressor-RobustScaler-no-outlayers-2.csv', index=False)

print("El DataFrame ha sido guardado en la carpeta 'predictions'.")

El DataFrame ha sido guardado en la carpeta 'predictions'.